### ISSUE TITLE
server barfs unicode error not fails on hebrew names

### ISSUE THREAD

**Issue by alon** [Rhizi/rhizi#319]
#שלום לי #היום

malformed label: לי
Traceback (most recent call last):
  File "/home2/alon/rhizi/rhizi/src/server/rz_api_rest.py", line 66, in diff_commit__topo
    _, commit_ret = kernel.diff_commit__topo(topo_diff, ctx)
  File "/home2/alon/rhizi/rhizi/src/server/rz_mesh.py", line 94, in wrapped_function
    f_ret = f(*args, **kw)
  File "/home2/alon/rhizi/rhizi/src/server/rz_kernel.py", line 38, in diff_commit__topo
    op = DBO_diff_commit__topo(topo_diff)
  File "/home2/alon/rhizi/rhizi/src/server/db_op.py", line 355, in __init__
    op = DBO_add_link_set(l_add_map)
  File "/home2/alon/rhizi/rhizi/src/server/db_op.py", line 119, in __init__
    for q, q_param_set in db_util.gen_query_create_from_link_map(link_map):
  File "/home2/alon/rhizi/rhizi/src/server/neo4j_util.py", line 245, in gen_query_create_from_link_map
    assert len(l_type) > 0 and l_type[0].isupper(), 'malformed label: ' + l_type
AssertionError: malformed label: \u05dc\u05d9
None
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home2/alon/rhizi/rhizi/src/server/rz_api_rest.py", line 71, in diff_commit__topo
    return common_resp_handle(error=e)
  File "/home2/alon/rhizi/rhizi/src/server/rz_req_handling.py", line 69, in common_resp_handle
    error_str = str(error)  # convert any Exception objects to serializable form
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)

**Comment by alon** [comment]
Closed in current release
