### ISSUE TITLE
UnicodeError of unknown origin

### ISSUE THREAD

**Issue by alon** [Rhizi/rhizi#637]
127.0.0.1 - - [2015-10-21 22:30:33] "GET /rz/Welcome%20Rhizi HTTP/1.1" 200 8172 0.001529
Traceback (most recent call last):
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/gevent/pywsgi.py", line 410, in handle
    result = self.handle_one_request()
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/gevent/pywsgi.py", line 625, in handle_one_request
    self.handle_one_response()
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/home2/alon/rhizi/rhizi/src/server/rz_mesh.py", line 80, in start_response
    return SocketIOHandler.start_response(self, status, headers, exc_info)
  File "/home2/alon/rhizi/venv/p2/lib/python2.7/site-packages/gevent/pywsgi.py", line 740, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7f1c8096a410: _close_when_done(<socket at 0x7f1c7a80acd0 fileno=[Errno 9] Bad fil, ('127.0.0.1', 47434))> failed with UnicodeError

**Comment by alon** [comment]
tracking issue: https://github.com/abourget/gevent-socketio/issues/228
